### ISSUE TITLE
Header and architecture images for README

### ISSUE THREAD

**Issue by pchittum** [authlete/.github#1]
Header: 
![Authlete GH Banner-01](https://github.com/authlete/.github/assets/1127876/eaeccebb-b1c1-45f7-befa-3c2451908288)

Architecture diagram: 
![api-request_01](https://github.com/authlete/.github/assets/1127876/ff3b6f0c-abc3-4777-92c9-12e50b1af8f8)

**Comment by pchittum** [comment]
Emblemt-only logo
![authlete-blue-emblem](https://github.com/authlete/.github/assets/1127876/a1d68ef2-6150-4fcc-923d-9b365acd0196)

Logo with text lock-up
![authlete-blue-horizontal-logo](https://github.com/authlete/.github/assets/1127876/2335571b-1976-4525-ac06-cf86893eebee)

**Comment by pchittum** [comment]
Trying the banner, but not quite as tall: 

![Authlete GH Banner-01-h1400](https://github.com/authlete/.github/assets/1127876/b3ed5ad8-adf9-4b58-9491-df9a7472e20c)

**Comment by shameelmazhar** [comment]
![GitHub Architecture Diagram](https://github.com/authlete/.github/assets/170624196/b7045441-322a-4ee2-8f28-42522326a9ec)
Please have a look and let me know if we need anything adjusted. I have not highlighted the "client_id-...&" sections yet but can do so

**Comment by shameelmazhar** [comment]
> Trying the banner, but not quite as tall:
> 
> ![Authlete GH Banner-01-h1400](https://private-user-images.githubusercontent.com/1127876/333156092-b3ed5ad8-adf9-4b58-9491-df9a7472e20c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjIzNjAsIm5iZiI6MTcxNjQ2MjA2MCwicGF0aCI6Ii8xMTI3ODc2LzMzMzE1NjA5Mi1iM2VkNWFkOC1hZGY5LTRiNTgtOTQ5MS1kZjlhNzQ3MmUyMGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMTEwMTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTg4NzM0MTY0NmM0MWY5Njk2ZjEwYzVkMjEyYzVkZTM1OTUwNDBhZjExYmMyOTlkNzkwMGZjZmQ4YmIzNTQzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aCCBAXHAGFPmC24O8rp3Lt2Vv25yL_DRneGd_6MESk8)

I used 1280 by 640 pixels - @pchittum can you suggest which height to use?

**Comment by pchittum** [comment]
> 
> I used 1280 by 640 pixels - @pchittum can you suggest which height to use?

The original I got from you was something like 5334 * 2600. I reduced the height to 1400 on this one.

**Comment by shameelmazhar** [comment]
> > I used 1280 by 640 pixels - @pchittum can you suggest which height to use?
> 
> The original I got from you was something like 5334 * 2600. I reduced the height to 1400 on this one.

Sorry about that must have been an error on my end, here's an updated version

![GitHub Banner](https://github.com/authlete/.github/assets/170624196/77aeb564-80ad-4bba-96c3-03fb2084db06)

**Comment by shameelmazhar** [comment]
@pchittum version with headers in Authlete Orange 
![GitHub Architecture Diagram v2](https://github.com/authlete/.github/assets/170624196/4b7bcb46-3321-4b6d-9ea2-92b0e0c29fbd)

**Comment by shameelmazhar** [comment]
version with headers in Authlete mid-grey
![GitHub Architecture Diagram v3](https://github.com/authlete/.github/assets/170624196/8f52efd2-4922-44fb-8b27-583f3a077b68)

**Comment by shameelmazhar** [comment]
Quick version of "enclosed" diagram
![GitHub Architecture Diagram v4](https://github.com/authlete/.github/assets/170624196/ce2abc2a-2793-4594-bcdb-4f76a2087f99)

**Comment by pchittum** [comment]
I really like the last one. What do you think?

**Comment by pchittum** [comment]
We are live! 💥 

See PR #2
